name: Build POT string index
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build and commit POT file
    steps:
      - name: Install gettext
        run: sudo apt-get install gettext
      - name: Checkout skytemple
        uses: actions/checkout@v2
        with:
          path: skytemple
      - name: Checkout skytemple-files
        uses: actions/checkout@v2
        with:
          repository: skytemple/skytemple-files
          path: skytemple-files
      - name: Checkout skytemple-dtef
        uses: actions/checkout@v2
        with:
          repository: skytemple/skytemple-dtef
          path: skytemple-dtef
      - name: Checkout skytemple-ssb-debugger
        uses: actions/checkout@v2
        with:
          repository: skytemple/skytemple-ssb-debugger
          path: skytemple-ssb-debugger
      - name: Checkout py-desmume
        uses: actions/checkout@v2
        with:
          repository: skytemple/py-desmume
          path: py_desmume
      - name: Checkout explorerscript
        uses: actions/checkout@v2
        with:
          repository: skytemple/explorerscript
          path: explorerscript
      - name: Checkout tilequant
        uses: actions/checkout@v2
        with:
          repository: skytemple/tilequant
          path: tilequant
      - name: Generate Strings
        run: |
          find . \
              -type f \
              \( \
                  -name "*.py" -or \
                  -name "*.glade" \
              \) \
              ! -path "py_desmume/desmume/frontend/PyDeSmuMe.glade" \
          | xargs xgettext \
              -F --keyword='_' --no-wrap --foreign-user \
              --package-name=skytemple --msgid-bugs-address=https://translate.skytemple.org \
              --add-comments='TRANSLATORS:' --from-code=UTF-8 \
              -o skytemple/skytemple/data/locale/skytemple.pot
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install skytemple-files
        run: |
          python -m pip install ./skytemple-files
      - name: Add ppmdu config strings
        run: |
          xgettext \
          -F --keyword='_' --no-wrap --foreign-user \
          --package-name=skytemple --msgid-bugs-address=https://translate.skytemple.org \
          -j --from-code=UTF-8 \
          -o skytemple/skytemple/data/locale/skytemple.pot \
          <(python -m skytemple_files.common.ppmdu_config.l10n_str_generator)
      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          add: skytemple/data/locale/skytemple.pot
          cwd: './skytemple'
          message: 'Github Actions: Update .pot string index'
          push: true
